@startuml
title 基于GitHub的实验管理平台--学生查看成绩用例的顺序图
actor students
teathers->college:选择学院
college->professional:选择专业
professional->termyear:选择学年
termyear->courses:选择课程
courses->test:选择相关实验
tests -> grades: 查看实验的成绩和评价
grades--> teathers:反馈给老师所有同学的实验
@enduml